package com.rooti.domain.document.application.journal.renderer;

import com.rooti.domain.document.application.JournalFormat;
import com.rooti.domain.document.application.PdfGenerator;
import com.rooti.domain.document.application.journal.JournalDocument;
import com.rooti.domain.document.application.journal.JournalDocument.Header;
import com.rooti.domain.document.application.journal.JournalDocument.LeaveEntry;
import com.rooti.domain.document.application.journal.JournalDocument.NextPlan;
import com.rooti.domain.document.application.journal.JournalDocument.ProcessRow;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * PDF 렌더러 — Rooti 브랜드 톤의 모던 HR 문서 양식으로 한 페이지를 그립니다.
 *
 * <p>레이아웃은 클라이언트의 {@code WorkJournalDocument.tsx} 와 1:1 매칭됩니다 (브랜드 스트립 →
 * 회사명 타이틀 → 업무 정보 → 휴가(조건부) → 업무 시간표 + 합계 푸터 → 특이사항 → 익일 업무
 * 계획 → Generated by 푸터). 두 렌더링이 같은 디자인 토큰을 공유하므로, 토큰 한 군데(=
 * {@code COLOR} / {@code Style}) 만 손대면 화면과 첨부 파일의 외관이 동시에 흘러갑니다.
 *
 * <p>데이터 가공은 {@link com.rooti.domain.document.application.journal.JournalDocumentAssembler}
 * 가 모두 끝낸 상태로 받아오므로, 본 클래스에는 표현 로직만 존재합니다.
 */
@Component
@RequiredArgsConstructor
public class PdfJournalRenderer implements JournalRenderer {

    /** 동일 토큰을 한곳에서만 유지 — 클라이언트의 TOKEN 객체와 1:1 매칭. */
    private static final class C {
        static final String PRIMARY = "#2f7fe8";
        static final String PRIMARY_SOFT = "#e8f0fe";
        static final String BORDER = "#e4e4e7";
        static final String BORDER_SOFT = "#f1f1f3";
        static final String TEXT = "#18181b";
        static final String MUTED = "#71717a";
        static final String SUBTLE = "#a1a1aa";
        static final String ROW_ALT = "#fafafa";
        static final String WARN_BG = "#fef9e8";
        static final String WARN_ACCENT = "#d97706";
        static final String WARN_LINE = "#fde68a";
    }

    private static final DateTimeFormatter GEN_AT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    private final PdfGenerator pdfGenerator;

    @Override
    public JournalFormat format() {
        return JournalFormat.PDF;
    }

    @Override
    public byte[] render(JournalDocument doc) {
        return pdfGenerator.renderHtmlToPdf(buildHtml(doc));
    }

    // ----- HTML 빌드 --------------------------------------------------------
    private String buildHtml(JournalDocument doc) {
        Header h = doc.header();
        StringBuilder sb = new StringBuilder(10 * 1024);
        sb.append("<!DOCTYPE html><html><head><meta charset='UTF-8'>");
        appendStyle(sb);
        sb.append("</head><body>");

        appendBrandStrip(sb);
        appendTitleBlock(sb, h);

        appendSectionHeader(sb, "업무 정보", C.PRIMARY);
        appendInfoCard(sb, h);

        if (!doc.leaves().isEmpty()) {
            appendSectionHeader(sb, "휴가", C.WARN_ACCENT);
            appendLeavesCard(sb, doc.leaves());
        }

        appendSectionHeader(sb, "업무 시간표", C.PRIMARY);
        appendProcessTable(sb, doc.rows());
        appendTotalsFooter(sb, doc.rows());

        sb.append("<div class='gap'></div>");
        appendSectionHeader(sb, "특이사항", C.PRIMARY);
        appendNotesBox(sb, doc.remarks());

        sb.append("<div class='gap'></div>");
        appendSectionHeader(sb, "익일 업무 계획", C.PRIMARY);
        appendNextPlansTable(sb, doc.nextPlans());

        appendGeneratedFooter(sb);

        sb.append("</body></html>");
        return sb.toString();
    }

    // ----- style ------------------------------------------------------------
    private static void appendStyle(StringBuilder sb) {
        sb.append("<style>")
                .append("@page { size: A4; margin: 18mm; }")
                .append("body { font-family:'NanumGothic','Pretendard','Malgun Gothic',sans-serif;")
                .append("  font-size:10.5pt; color:").append(C.TEXT).append("; line-height:1.55; }")
                // 브랜드 스트립
                .append(".brand { display:flex; justify-content:space-between; align-items:center;")
                .append("  margin-bottom:8px; }")
                .append(".brand b { color:").append(C.PRIMARY).append("; font-size:11pt; }")
                .append(".brand span { color:").append(C.SUBTLE).append("; font-size:9pt; }")
                .append(".brand-sep { height:1px; background:").append(C.BORDER).append("; margin-bottom:18px; }")
                // 타이틀
                .append("h1.company { font-size:20pt; margin:0; font-weight:700;")
                .append("  letter-spacing:-0.01em; color:").append(C.TEXT).append("; }")
                .append("p.subtitle { font-size:10.5pt; color:").append(C.MUTED).append(";")
                .append("  margin:4px 0 8px; }")
                .append(".accent-bar { width:36px; height:2.5px; background:").append(C.PRIMARY).append(";")
                .append("  margin-bottom:18px; }")
                // 섹션 헤더
                .append(".section { display:flex; align-items:center; gap:8px; margin-bottom:8px; }")
                .append(".section i { display:inline-block; width:3px; height:13px; }")
                .append(".section b { font-size:12pt; letter-spacing:-0.01em; font-weight:700; }")
                .append(".gap { height:18px; }")
                // 공용 카드/테이블
                .append(".card { border:1px solid ").append(C.BORDER).append("; border-radius:6px;")
                .append("  overflow:hidden; margin-bottom:16px; }")
                .append("table.j { width:100%; border-collapse:collapse; }")
                .append("table.j th, table.j td { padding:7px 10px; font-size:10pt; }")
                .append(".tabular { font-variant-numeric:tabular-nums; }")
                // 업무 정보
                .append(".info td.k { width:110px; background:").append(C.PRIMARY_SOFT).append(";")
                .append("  color:").append(C.PRIMARY).append("; font-weight:700;")
                .append("  border-bottom:1px solid ").append(C.BORDER_SOFT).append("; }")
                .append(".info td.v { color:").append(C.TEXT).append(";")
                .append("  border-bottom:1px solid ").append(C.BORDER_SOFT).append("; }")
                .append(".info tr:last-child td { border-bottom:none; }")
                // 휴가
                .append(".leaves { background:").append(C.WARN_BG).append("; border:1px solid ")
                .append(C.WARN_LINE).append("; border-radius:6px; padding:12px 14px;")
                .append("  margin-bottom:16px; }")
                .append(".leaves .ttl { color:").append(C.WARN_ACCENT).append("; font-weight:700;")
                .append("  margin:0 0 6px; font-size:10pt; }")
                .append(".leaves .row { font-size:10pt; margin:3px 0; }")
                .append(".leaves .row b { color:").append(C.WARN_ACCENT).append(";")
                .append("  font-weight:700; margin-right:6px; }")
                // 업무 시간표 / 익일계획
                .append("table.j thead th { background:").append(C.PRIMARY_SOFT).append(";")
                .append("  color:").append(C.PRIMARY).append("; font-weight:700;")
                .append("  font-size:9.5pt; }")
                .append("table.j tbody td { border-top:0.5px solid ").append(C.BORDER_SOFT).append("; }")
                .append("table.j tbody tr.alt td { background:").append(C.ROW_ALT).append("; }")
                .append("td.c { text-align:center; }")
                .append("td.l { text-align:left; }")
                .append("td.r { text-align:right; }")
                .append("td.rest { color:").append(C.MUTED).append("; font-weight:400; }")
                .append("td.work { color:").append(C.TEXT).append("; font-weight:600; }")
                .append("td.note { color:").append(C.MUTED).append("; }")
                .append(".totals { text-align:right; color:").append(C.MUTED).append(";")
                .append("  font-size:9.5pt; margin:6px 0 0; }")
                // 특이사항
                .append(".notes { border:1px solid ").append(C.BORDER).append("; border-radius:6px;")
                .append("  padding:10px 14px; min-height:64px; font-size:10pt; }")
                // 생성 푸터
                .append(".gen-sep { height:0.6px; background:").append(C.BORDER).append(";")
                .append("  margin-top:24px; }")
                .append(".gen { color:").append(C.SUBTLE).append("; font-size:9pt; margin:6px 0 0; }")
                .append("</style>");
    }

    // ----- section helpers --------------------------------------------------
    private static void appendBrandStrip(StringBuilder sb) {
        sb.append("<div class='brand'><b>Rooti</b>")
                .append("<span>Work Journal · 근무일지</span></div>")
                .append("<div class='brand-sep'></div>");
    }

    private static void appendTitleBlock(StringBuilder sb, Header h) {
        sb.append("<h1 class='company'>").append(esc(h.companyName())).append("</h1>")
                .append("<p class='subtitle'>")
                .append(esc(h.dateLabelKor())).append(" &nbsp;·&nbsp; ")
                .append(esc(h.workerName()))
                .append(h.workerRank() == null || h.workerRank().isEmpty()
                        ? ""
                        : " (" + esc(h.workerRank()) + ")")
                .append("</p>")
                .append("<div class='accent-bar'></div>");
    }

    private static void appendSectionHeader(StringBuilder sb, String label, String accent) {
        sb.append("<div class='section'><i style='background:").append(accent).append("'></i>")
                .append("<b>").append(esc(label)).append("</b></div>");
    }

    private static void appendInfoCard(StringBuilder sb, Header h) {
        sb.append("<div class='card'><table class='j info'><tbody>");
        appendInfoRow(sb, "업무명", h.jobStandardName());
        appendInfoRow(sb, "직급", h.workerRank());
        appendInfoRow(sb, "성명", h.workerName());
        appendInfoRow(sb, "일자", h.dateLabelKor());
        sb.append("</tbody></table></div>");
    }

    private static void appendInfoRow(StringBuilder sb, String key, String value) {
        sb.append("<tr><td class='k c'>").append(esc(key)).append("</td>")
                .append("<td class='v l'>").append(esc(value)).append("</td></tr>");
    }

    private static void appendLeavesCard(StringBuilder sb, List<LeaveEntry> leaves) {
        sb.append("<div class='leaves'>")
                .append("<p class='ttl'>휴가 · 이 날 근무가 휴가로 처리되었습니다</p>");
        for (LeaveEntry l : leaves) {
            sb.append("<p class='row'><b>").append(esc(l.type().label())).append("</b>")
                    .append("<span class='tabular' style='color:").append(C.MUTED).append("'>")
                    .append(esc(l.rangeLabel())).append("</span>")
                    .append(" <span style='color:").append(C.SUBTLE).append("'>· ").append(l.days()).append("일</span>")
                    .append(l.reason() == null || l.reason().isEmpty()
                            ? ""
                            : " <span>· " + esc(l.reason()) + "</span>")
                    .append("</p>");
        }
        sb.append("</div>");
    }

    private static void appendProcessTable(StringBuilder sb, List<ProcessRow> rows) {
        sb.append("<div class='card'><table class='j'><colgroup>")
                .append("<col style='width:22%'><col style='width:46%'>")
                .append("<col style='width:12%'><col style='width:20%'>")
                .append("</colgroup>")
                .append("<thead><tr><th class='c'>업무 시간</th><th class='l'>업무 내용</th>")
                .append("<th class='c'>시간</th><th class='l'>비고</th></tr></thead><tbody>");
        if (rows.isEmpty()) {
            sb.append("<tr><td class='c' colspan='4' style='color:").append(C.SUBTLE)
                    .append(";padding:14px'>기록된 작업이 없습니다.</td></tr>");
        } else {
            for (int i = 0; i < rows.size(); i++) {
                ProcessRow r = rows.get(i);
                boolean rest = r.label() != null && r.label().contains("휴식");
                sb.append("<tr").append(i % 2 == 1 ? " class='alt'" : "").append(">")
                        .append("<td class='c tabular' style='color:").append(C.MUTED).append("'>")
                        .append(esc(r.startTime())).append(" – ").append(esc(r.endTime()))
                        .append("</td>")
                        .append(rest ? "<td class='l rest'>" : "<td class='l work'>")
                        .append(esc(r.label())).append("</td>")
                        .append("<td class='c tabular'>").append(r.durationMinutes()).append("분</td>")
                        .append("<td class='l note'>").append(esc(r.note())).append("</td>")
                        .append("</tr>");
            }
        }
        sb.append("</tbody></table></div>");
    }

    private static void appendTotalsFooter(StringBuilder sb, List<ProcessRow> rows) {
        long rest =
                rows.stream()
                        .filter(r -> r.label() != null && r.label().contains("휴식"))
                        .mapToLong(ProcessRow::durationMinutes)
                        .sum();
        long total = rows.stream().mapToLong(ProcessRow::durationMinutes).sum();
        long work = total - rest;
        sb.append("<p class='totals'>합계 근무 ").append(formatHm(work))
                .append(" &nbsp;·&nbsp; 휴식 ").append(formatHm(rest))
                .append(" &nbsp;·&nbsp; 총 체류 ").append(formatHm(total))
                .append("</p>");
    }

    private static void appendNotesBox(StringBuilder sb, String text) {
        sb.append("<div class='notes'>").append(esc(text)).append("</div>");
    }

    private static void appendNextPlansTable(StringBuilder sb, List<NextPlan> plans) {
        sb.append("<div class='card'><table class='j'><colgroup>")
                .append("<col style='width:38%'><col style='width:20%'><col style='width:42%'>")
                .append("</colgroup>")
                .append("<thead><tr><th class='c'>업무</th><th class='c'>예상 시간</th>")
                .append("<th class='l'>지시사항</th></tr></thead><tbody>");
        for (NextPlan p : plans) {
            sb.append("<tr>")
                    .append("<td class='c work'>").append(esc(p.task())).append("</td>")
                    .append("<td class='c tabular' style='color:").append(C.MUTED).append("'>")
                    .append(p.expectedMinutes() == null ? "" : p.expectedMinutes() + "분")
                    .append("</td>")
                    .append("<td class='l'>").append(esc(p.instruction())).append("</td>")
                    .append("</tr>");
        }
        sb.append("</tbody></table></div>");
    }

    private static void appendGeneratedFooter(StringBuilder sb) {
        sb.append("<div class='gen-sep'></div>")
                .append("<p class='gen'>Generated by Rooti · ")
                .append(GEN_AT.format(OffsetDateTime.now()))
                .append("</p>");
    }

    private static String formatHm(long minutes) {
        long h = minutes / 60;
        long m = minutes % 60;
        return h + "시간 " + String.format("%02d", m) + "분";
    }

    private static String esc(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
